on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' 
          java-version: '17'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: '3.19.6'
          channel: 'stable'
          cache: true
      # - run: flutter clean 
      - run: flutter pub get 
      # - run: flutter build appbundle 
      - run: flutter build apk --split-per-abi
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Get pubspec version
        id: version
        run: |
          VERSION=$(grep -oP 'version: \K.*(?=</)' pubspec.yaml)
          echo "::set-output name=version::$VERSION"
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "build/app/outputs/apk/release/*.apk,build/ios/iphoneos/app.ipa"
          # tag: v2.1.${{ github.run_number }}
          tag: $v{{ steps.version.outputs.version }}"
          token: ${{ secrets.TOKEN }}
